### ISSUE TITLE
Dependencies clash around com.jayway.jsonpath and excluded minidev library

### ISSUE THREAD

**Issue by nantipov** [zalando/logbook#1074]
After `logbook-spring-boot-starter` version `2.10.0` the versions clash might appear around the library `com.jayway.jsonpath` and excluded sub-dependency `minidev`.

## Description

The `logbook` library uses the highest version of the `com.jayway.jsonpath` at the moment. Meanwhile the sub-dependency `minidev` was excluded. However, a target project itself might involve the same dependency but with a lower version. This could "hide" the `minidev` library from an entire project.

The issue was caught in the project based on the `Spring` with the `Gradle` toolchain. As of conflict resolution the highest version (from `logbook`) is taken where the sub-depencency `minidev` was excluded (#1036). At lease it is how I see it.

```xml
            <!-- JsonPath -->
            <dependency>
                <groupId>com.jayway.jsonpath</groupId>
                <artifactId>json-path</artifactId>
                <version>${json-path.version}</version>
                <exclusions>
                    <!-- we configure json path to use jackson therefore we do not need json-smart -->
                    <exclusion>
                        <groupId>net.minidev</groupId>
                        <artifactId>json-smart</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

## Expected Behavior
Normal application startup.

## Actual Behavior
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Factory method 'requestMappingHandlerAdapter' threw exception; nested exception is java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        ...
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Factory method 'requestMappingHandlerAdapter' threw exception; nested exception is java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI
	at com.jayway.jsonpath.internal.DefaultsImpl.<init>(DefaultsImpl.java:17)
	at com.jayway.jsonpath.internal.DefaultsImpl.<clinit>(DefaultsImpl.java:15)
	at com.jayway.jsonpath.Configuration.getEffectiveDefaults(Configuration.java:43)
	at com.jayway.jsonpath.Configuration.access$000(Configuration.java:29)
	at com.jayway.jsonpath.Configuration$ConfigurationBuilder.build(Configuration.java:224)
	at org.springframework.data.web.JsonProjectingMethodInterceptorFactory.<init>(JsonProjectingMethodInterceptorFactory.java:75)
	at org.springframework.data.web.ProjectingJackson2HttpMessageConverter.initProjectionFactory(ProjectingJackson2HttpMessageConverter.java:87)
	at org.springframework.data.web.ProjectingJackson2HttpMessageConverter.<init>(ProjectingJackson2HttpMessageConverter.java:72)
	at org.springframework.data.web.config.SpringDataWebConfiguration.extendMessageConverters(SpringDataWebConfiguration.java:169)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurerComposite.extendMessageConverters(WebMvcConfigurerComposite.java:144)
	at org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.extendMessageConverters(DelegatingWebMvcConfiguration.java:123)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.getMessageConverters(WebMvcConfigurationSupport.java:869)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerAdapter(WebMvcConfigurationSupport.java:673)
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.requestMappingHandlerAdapter(WebMvcAutoConfiguration.java:423)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 28 common frames omitted
Caused by: java.lang.ClassNotFoundException: net.minidev.json.writer.JsonReaderI
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 common frames omittedf
```

## Possible Fix

Please correct me if I am wrong, but it seems the `net.minidev` dependency should be not excluded.

## Steps to Reproduce

1. Create an empty `Gradle` `Java` application based on `Spring Boot 2.5.1`
2. Ensure the following dependencies.
- 'org.springframework.boot:spring-boot-starter-undertow' 
- 'org.springframework.boot:spring-boot-starter-web'
- 'org.springframework.boot:spring-boot-starter-actuator'
- 'org.springframework.boot:spring-boot-starter-data-jpa'
- 'logbook-spring-boot-starter:2.10.0'
3. Run application
4.

## Context

No major concern, fail on dependency version update 'logbook-spring-boot-starter' `2.9.0` -> `2.10.0`.

## Your Environment

* Version used: 2.10.0
* Link to your project: n/a

Thank you.

**Comment by whiskeysierra** [comment]
The stacktrace doesn't suggest that logbook is even involved.

**Comment by nantipov** [comment]
@whiskeysierra Thanks for getting back to me on this. Yes, it is true, the stacktrace does not indicate involvement of the `logbook`.

The issue is around "hidden" dependency (`java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI`). The dependency `net.minidev:json-smart` was excluded with a corresponding directive in the `pom` file (https://github.com/zalando/logbook/pull/1036/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8).

However, in the sample project the `logbook` is not the only library which uses the `net.minidev:json-smart` and `com.jayway.jsonpath`. Here the Spring also has such a dependency. But `logbook` uses the highest version of the `com.jayway.jsonpath` in the project, so `gradle` keeps it as a main one for all other users (libraries). And that main one version of `com.jayway.jsonpath` depends on the `net.minidev:json-smart` which was excluded.

Therefore, other users (e.g. Spring) fail because absence of `net.minidev:json-smart` is crucial for them. Maybe I am wrong, but that is how I see the problem.

**Comment by whiskeysierra** [comment]
But then there are two fixes which would be correct:

1. Direct dependency to json-smart within your project.
2. Manually, statically configure jsonpath to use jackson, also within your project.

Both are fine, but neither belongs to Logbook.
This is a dependency issue with Maven. Logbook doesn't need json-smart, so it shouldn't be Logbooks responsibility to fix another dependency which does.

**Comment by sokomishalov** [comment]
I've provided both workarounds for logbook-spring-autoconfigure (https://github.com/zalando/logbook/pull/1087) and fix for spring-data-commons, which causes it (https://github.com/spring-projects/spring-data-commons/pull/2403)

**Comment by nantipov** [comment]
@whiskeysierra thanks for feedback.

Yes, of course, there are many solutions around it:
- open a ticket in Spring;
- stop using Spring;
- reconfigure Spring;
- manually bring additional transitive dependency into project;
- stop bumping version of `logbook` after `2.9.0`;
- exclude `com.jayway.jsonpath` (not just `json-smart`) from `logbook` on project level.

Some of those solutions are quite hacky and temporary ones. Here it is mostly about practice of using or not using directives such `exclude` in libraries which are designed to be a part of a big project.

Of course, I am not insisting on anything, but after version `2.10.0` (inclusive) `logbook` users have to build hacky workarounds. It is fine as solutions exist in general, but it is not a fully clean approach.

Thank you!

**Comment by whiskeysierra** [comment]
> Here it is mostly about practice of using or not using directives such `exclude` in libraries which are designed to be a part of a big project.

But from Logbook's perspective that is the correct thing to do. We don't need it, we don't want it, we don't depend on it. The classpath of our users stays clean. It's really a Maven issue because if two dependencies have the same transitive dependency but one of them exclude a transitive dependency of that transitive dependency then Maven should do the right thing and not exclude it, since it's needed by someone else.

**Comment by mp911de** [comment]
There are a few aspects here. Spring Data is doing the right thing, it uses the configuration builder API that applies defaults. It is more the `DefaultsImpl` that doesn't expect the absence of `minidev`. It would make sense to bring this discussion to `jsonpath`.

Adding flexibility on the Spring side would certainly allow for further options.

**Comment by whiskeysierra** [comment]
> Spring Data is doing the right thing, it uses the configuration builder API that applies defaults.

Agreed, Spring Data is doing nothing wrong here.

> It is more the `DefaultsImpl` that doesn't expect the absence of `minidev`.

Why should it? The default dependencies (if you don't exclude anything) include minidev. Everything is good here too.

**If** someone excludes a dependency, they should also change their configuration to make sure they don't actually depend on it. Spring Data is doing this. And so does Logbook. I see Maven at fault, because if you have two dependencies which depend on the same thing, but one of them excludes a transitive dependency while the one doesn't (which means it depends on it), then Maven should **not** exclude that transitive dependency.

**Comment by mp911de** [comment]
> Why should it? The default dependencies (if you don't exclude anything) include minidev. Everything is good here too.

jsonpath ships with various mapper and provider implementations so having a class path check on their side seems a sensible approach to determine defaults.

**Comment by sokomishalov** [comment]
The fix is available in spring-data-commons v2.5.3 (spring-data BOM v2021.0.3, spring-boot BOM v2.5.3) - huge thanks to @mp911de.
I propose to merge this [spring-boot dependency upgrade](https://github.com/zalando/logbook/pull/1099) to prevent further errors/failures/issues.

**Comment by sokomishalov** [comment]
@whiskeysierra I suppose it's not reproducible on spring-boot 2.5.3 bom so I think we should close it.
@nantipov please confirm it

**Comment by nantipov** [comment]
Thanks you @mp911de , @sokomishalov and @whiskeysierra .
Yes, we can closed the issue.
