### ISSUE TITLE
How to obfuscate JSON responses by URL?

### ISSUE THREAD

**Issue by kurtinaitis** [zalando/logbook#1185]
I need to obfuscate JSON responses coming from certain URLs.
In a log configuration with jsonPath body filter (`Logbook.builder().bodyFilter(jsonPath(`) it tries to apply to all possible responses and fails because their structure does not match.

When I try to build a custom ResponseFilter, I cannot find the URL request.

Any ideas?

**Comment by whiskeysierra** [comment]
> When I try to build a custom ResponseFilter, I cannot find the URL request.

The request data is not available to response filters.

> it tries to apply to all possible responses and fails because their structure does not match.

That's an interesting one. Can you share details on this, incl. configuration, sample request and exception stack trace?

**Comment by kurtinaitis** [comment]
Configuration:
```
	@Bean
	BodyFilter bodyFilter() {
		return jsonPath("$.individual.gender").replace("X");
	}
```
Response is actually a JSON array, which I don't want to include here :-(
```
[{"name":"NNN","number":1001,"countryCode":"NO"}, ...]
```
Stack trace:
```
2021-10-04 11:18:33.699 ERROR 1781661 --- [nio-9060-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['individual'] in path $ but found 'com.fasterxml.jackson.databind.node.ArrayNode'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JacksonJsonNodeJsonProvider'.
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:71)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
	at com.jayway.jsonpath.JsonPath.set(JsonPath.java:220)
	at com.jayway.jsonpath.internal.JsonContext.set(JsonContext.java:132)
	at org.zalando.logbook.json.JsonPathBodyFilters$JsonPathBodyFilterBuilder.lambda$replace$1(JsonPathBodyFilters.java:58)
	at org.zalando.logbook.json.JsonPathBodyFilters$JsonPathBodyFilter.filter(JsonPathBodyFilters.java:99)
	at org.zalando.logbook.FilteredHttpResponse.getBodyAsString(FilteredHttpResponse.java:50)
	at org.zalando.logbook.DefaultHttpLogFormatter.format(DefaultHttpLogFormatter.java:63)
	at org.zalando.logbook.DefaultSink.write(DefaultSink.java:26)
	at org.zalando.logbook.Strategy.write(Strategy.java:119)
	at org.zalando.logbook.DefaultLogbook$1.lambda$process$0(DefaultLogbook.java:55)
	at org.zalando.logbook.servlet.LogbookFilter.write(LogbookFilter.java:87)
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:80)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
```

**Comment by kurtinaitis** [comment]
I see. The problem is most probably the JSON array as a response. Because several previous JSON responses are happily ignored by the body filter.
Jsonpath docs say the array should not be a problem. Some integration issue?

**Comment by skjolber** [comment]
Hi, I made a somewhat related [module](https://github.com/skjolber/json-log-filter/tree/master/frameworks/spring-boot-starter-logbook) some time ago. The main goal was increased performance, not jsonpath-issues.

**Comment by whiskeysierra** [comment]
We have tests for those cases:

https://github.com/zalando/logbook/blob/2d5b00978709ca0d7a0bd9fc13cc92288bc9d0fe/logbook-json/src/test/java/org/zalando/logbook/json/JsonPathBodyFiltersTest.java#L236-L260
