### ISSUE TITLE
LogbookClientHttpRequestInterceptor incompatible with Spring boot 2.7/Spring 5

### ISSUE THREAD

**Issue by nongagf** [zalando/logbook#1580]
## Description
Using LogbookClientHttpRequestInterceptor in a Spring boot 2 project leads to NuSuchMethod errors when handling client responses. It seems the return type of `org.springframework.http.client.ClientHttpResponse.getStatusCode()` has changed in Spring 6.

Logging outbound client requests works fine.

## Expected Behavior
Inbound client response is logged.

## Actual Behavior
```
java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatusCode org.springframework.http.client.ClientHttpResponse.getStatusCode()'

	at org.zalando.logbook.spring.RemoteResponse.getStatus(RemoteResponse.java:109)
	at org.zalando.logbook.ForwardingHttpResponse.getStatus(ForwardingHttpResponse.java:17)
	at org.zalando.logbook.ForwardingHttpResponse.getStatus(ForwardingHttpResponse.java:17)
	at org.zalando.logbook.StructuredHttpLogFormatter.prepare(StructuredHttpLogFormatter.java:92)
	at org.zalando.logbook.StructuredHttpLogFormatter.format(StructuredHttpLogFormatter.java:26)
	at org.zalando.logbook.logstash.LogstashLogbackSink.write(LogstashLogbackSink.java:52)
	at org.zalando.logbook.Strategy.write(Strategy.java:119)
	at org.zalando.logbook.core.DefaultLogbook$1.lambda$process$0(DefaultLogbook.java:65)
	at org.zalando.logbook.spring.LogbookClientHttpRequestInterceptor.intercept(LogbookClientHttpRequestInterceptor.java:28)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93)
```

## Steps to Reproduce
1. Configure a RestTemplate with LogbookClientHttpRequestInterceptor
```
  @Bean
  RestTemplate restTemplate(LogbookClientHttpRequestInterceptor interceptor) {
    RestTemplate restTemplate =
        new RestTemplateBuilder()
            .additionalInterceptors(interceptor)
            .build();
    return restTemplate;
  }
```
2. Send a request
3. Error happens when the client response is handled

## Your Environment
* Version used: 3.1.0
* Spring boot version: 2.7.13

**Comment by nongagf** [comment]
Fixed in 3.2.0
