### ISSUE TITLE
UnsupportedOperationException: null when using logbook-httpclient (4.0)

### ISSUE THREAD

**Issue by UBaggeler** [zalando/logbook#1734]
## Description
When using logbook-httpclient (4.0) to log SOAP requests (Axis2), we are getting an `java.lang.UnsupportedOperationException: null`. This seems to be the same issue as recently fixed in logbook-httpclient5 (https://github.com/zalando/logbook/issues/1693) with PR https://github.com/zalando/logbook/pull/1701.

```
java.lang.UnsupportedOperationException: null
	at org.apache.axis2.transport.http.impl.httpclient4.AxisRequestEntityImpl.getContent(AxisRequestEntityImpl.java:57)
	at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:124)
	at org.zalando.logbook.httpclient.HttpEntities.copy(HttpEntities.java:22)
	at org.zalando.logbook.httpclient.LocalRequest$Offering.buffer(LocalRequest.java:83)
	at org.zalando.logbook.httpclient.LocalRequest.lambda$getBody$3(LocalRequest.java:245)
	at org.zalando.fauxpas.ThrowingFunction.apply(ThrowingFunction.java:19)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.zalando.logbook.httpclient.LocalRequest.getBody(LocalRequest.java:244)
	at org.zalando.logbook.HttpMessage.getBodyAsString(HttpMessage.java:44)
	at org.zalando.logbook.ForwardingHttpMessage.getBodyAsString(ForwardingHttpMessage.java:47)
	at org.zalando.logbook.core.FilteredHttpRequest.getBodyAsString(FilteredHttpRequest.java:92)
	at org.zalando.logbook.StructuredHttpLogFormatter.prepareBody(StructuredHttpLogFormatter.java:120)
	at org.zalando.logbook.StructuredHttpLogFormatter.prepare(StructuredHttpLogFormatter.java:72)
	at org.zalando.logbook.StructuredHttpLogFormatter.format(StructuredHttpLogFormatter.java:20)
	at org.zalando.logbook.core.DefaultSink.write(DefaultSink.java:27)
	at org.zalando.logbook.Strategy.write(Strategy.java:69)
	at org.zalando.logbook.core.DefaultLogbook$1.write(DefaultLogbook.java:60)
	at org.zalando.logbook.httpclient.LogbookHttpRequestInterceptor.process(LogbookHttpRequestInterceptor.java:26)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.axis2.transport.http.impl.httpclient4.RequestImpl.execute(RequestImpl.java:210)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:194)
	at org.apache.axis2.transport.http.AbstractHTTPTransportSender.writeMessageWithCommons(AbstractHTTPTransportSender.java:386)
	at org.apache.axis2.transport.http.AbstractHTTPTransportSender.invoke(AbstractHTTPTransportSender.java:214)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:431)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:399)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:150)
```

## Expected Behavior
No exception

## Actual Behavior
UnsupportedOperationException

## Possible Fix
See https://github.com/zalando/logbook/pull/1701

## Steps to Reproduce

1. Add `LogbookHttpRequestInterceptor` to the `HttpClientBuilder` via `addInterceptorFirst`
2. Make a (Axis2) request which fails

## Your Environment

Version used:

- Logbook: 3.7.2
- Spring Boot: 2.7
- Apache Http Client: 4.5.14

**Comment by kasmarian** [comment]
@UBaggeler thank you for raising this. We'll add the fix in the next release
