### ISSUE TITLE
Request fails when using a streaming response in spring boot apps

### ISSUE THREAD

**Issue by sgandon** [zalando/logbook#185]
Hello,
I am experimenting with logbook and wanted to try to see how it behaves with streams and asynchronous responses.
I have created a small example to show the issue [here](https://github.com/sgandon/test-zalando-stream)
When I set the `logbook.write.level=INFO` and call the endpoint this just breaks the request completely

The stack trace is quite big but we can see the following messages.

> Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
> java.nio.BufferOverflowException: null
> and some NPEs.

**Comment by whiskeysierra** [comment]
Logbook works on the assumption that it can buffer the whole request/response before logging it (since it logs exactly once). This is not possible for streaming, since there is no single point in time when you could log something.

The only way logbook deals with that situation is to disable logging of the body for this requests/responses. By default, it will disable body logging for the following media types:
- application/octet-stream
- application/pdf
- audio/*
- image/*
- video/*
- multipart/*
- application/json-seq
- application/x-json-stream

For those bodies, we will just log something like `<stream>`.

I guess Spring uses a different media type. Do you know which one? `text/event-stream`? I'll add it to the default list. Alternatively, you can specify a custom request/response yourself:

```java
Logbook.builder()
    .rawRequestFilter(replaceBody(contentType("text/event-stream"), "<stream>"))
    .rawResponseFilter(replaceBody(contentType("text/event-stream"), "<stream>"))
    .build();
```

**Comment by sgandon** [comment]
sorry to have not given any response earlier, I have not a lot of knowledge on spring rest handling but it seems to be possible to have a stream returned and no content type specified in the response header. So I was wondering if logbook should not simple ignore the body when there is no content type specified in the response ?

**Comment by whiskeysierra** [comment]
> it seems to be possible to have a stream returned and no content type specified in the response header

That's unfortunate, but definitely something that should be supported somehow.

> So I was wondering if logbook should not simple ignore the body when there is no content type specified in the response

I wouldn't use it as a default behaviour, but it would be useful to configure that. I'll think about it.

**Comment by whiskeysierra** [comment]
This could be an option:

```java
rawResponseFilter(replaceBody(contentType(null), "<stream>"))
```

**Comment by sgandon** [comment]
the proposal above creates a nice NPE
```
Caused by: java.lang.NullPointerException: null
	at java.util.Arrays.stream(Arrays.java:5004)
	at org.zalando.logbook.MediaTypeQuery.compile(MediaTypeQuery.java:19)
	at org.zalando.logbook.Conditions.contentType(Conditions.java:47)
	at org.talend.components.service.rest.configuration.ApiVersionConfig.setupLogBook(ApiVersionConfig.java:39)
```
I have also tried with the content type empty ("") and I have another exception
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.zalando.logbook.MediaTypeQuery.compile(MediaTypeQuery.java:30)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at org.zalando.logbook.MediaTypeQuery.compile(MediaTypeQuery.java:21)
	at org.zalando.logbook.Conditions.contentType(Conditions.java:47)
	at org.talend.components.service.rest.configuration.ApiVersionConfig.setupLogBook(ApiVersionConfig.java:39)
```

**Comment by whiskeysierra** [comment]
My wording was poor. With *option* I meant that this could be an option how to support it. It won't work right now, as you verified. The second exception is expected and not subject to change since an empty string is not a valid media type.

**Comment by whiskeysierra** [comment]
@sgandon I created #188 to support querying for absent (`null`) content types.

**Comment by AlexanderYastrebov** [comment]
@whiskeysierra 
What do you think about adding a new helper method
`Conditions.withoutContentType()` instead of using `Conditions.contentType(null)`?

**Comment by whiskeysierra** [comment]
Good idea. I'll update the PR.
