### ISSUE TITLE
Support Spring 5 and Spring Boot 2

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/logbook#194]

**Comment by wreulicke** [comment]
@whiskeysierra 
Are there any remaining tasks?

**Comment by whiskeysierra** [comment]
It might work already. Did you give it a try?

**Comment by wreulicke** [comment]
> It might work already. Did you give it a try?

I did not try. I will try it.

**Comment by FlowerWrong** [comment]
It worked for me.

spring boot 2.0.1

**Comment by whiskeysierra** [comment]
Sounds like we need to update some docs.

**Comment by atrujillofalcon** [comment]
He migrado mi aplicación a Spring Boot 2.0.2-RELEASE y ahora al tratar de arrancar el servicio me lanza un error:

`java.lang.NoClassDefFoundError: org/springframework/boot/bind/RelaxedPropertyResolver
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getExcludeAutoConfigurationsProperty(AutoConfigurationImportSelector.java:215)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getExclusions(AutoConfigurationImportSelector.java:209)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.selectImports(AutoConfigurationImportSelector.java:99)
	at org.springframework.context.annotation.ConfigurationClassParser$DefaultDeferredImportSelectorGroup.process(ConfigurationClassParser.java:841)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:827)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:560)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
	at `

If I comment the **logbook-spring-boot-starter** from the pom.xml the service starts normally.

I'm using logbook version **1.7.3**

**Comment by whiskeysierra** [comment]
@atrujillofalcon Is that the full stacktrace?

**Comment by atrujillofalcon** [comment]
@whiskeysierra I've realized the cause of the issue. When I import the logbook-spring-boot-starter Maven automatically includes in the classpath the org.springframework.boot:spring-boot-autoconfigure:1.5.10.RELEASE dependency (wrong version, clash with new SB2 autoconfigure dependency).

I've been able to fix it adding a Maven exclusion, but it's just a workaround:

`<dependency>
            <groupId>org.zalando</groupId>
            <artifactId>logbook-spring-boot-starter</artifactId>
            <version>1.7.3</version>
            <exclusions>
                
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-autoconfigure</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by whiskeysierra** [comment]
I'm preparing a pull request as we speak in order to set the scope to provided. That should solve it.

**Comment by atrujillofalcon** [comment]
Thanks @whiskeysierra . I will keep the exclusion until the next version that includes this fix is released.
