### ISSUE TITLE
No suitable driver found for 08001/0

### ISSUE THREAD

**Issue by KiselevAlecksey** [zalando/logbook#1965]
Issue Description
I am encountering the error No suitable driver found for 08001/0 when I add the following dependency in Maven: 

```
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-spring-boot-starter</artifactId>
    <version>3.7.2</version>
</dependency>
```

minimum maven dependencies for repeat
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.example</groupId>
    <artifactId>test</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>logbook-spring-boot-starter</artifactId>
            <version>3.7.2</version>
        </dependency>
    </dependencies>
```

Expected Behavior
I expected to be able to access the H2 console.

Actual Behavior
Instead, the following error occurs:

```
java.sql.SQLException: No suitable driver found for
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
    at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
    at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:335)
```

Possible Fix
It is necessary to check whether the JDBC driver for H2 is installed and correctly configured.

Steps to Reproduce
1. Add the dependency in Maven.
2. Attempt to access the H2 console.

Context
The goal is to connect to the H2 console to work with the database.

Your Environment
 Version used: 3.7.2

[* StackOwerflow ](https://stackoverflow.com/questions/39854172/h2-console-error-no-suitable-driver-found-for-08001-0)

**Comment by kasmarian** [comment]
Is the persists when you remove logbook from the dependencies? I fail to understand the connection here with h2 driver.
