### ISSUE TITLE
Unable to start application because MBean `httpLogger` is already registered

### ISSUE THREAD

**Issue by vishnukvmd** [zalando/logbook#410]
Application startup is failing while registering the MBean of `SlfTTLogger` because it looks like an MXBean of `SlfTTLoggerFactory` is already registered under the same name.

## Logs
```
2019-01-17 15:53:25,295 4619 [main] INFO  [o.s.j.e.a.AnnotationMBeanExporter] {{appResourceId,vg@dev}} - Located MBean 'httpLogger': registering with JMX server as MBean [org.slf4j.impl:name=httpLogger,type=SlfTTLogger]
2019-01-17 15:53:25,296 4620 [main] INFO  [o.s.j.e.a.AnnotationMBeanExporter] {{appResourceId,vg@dev}} - Unregistering JMX-exposed beans
2019-01-17 15:53:25,327 4651 [main] INFO  [o.s.b.a.l.ConditionEvaluationReportLoggingListener] {{appResourceId,vg@dev}} -
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-01-17 15:53:25,330 4654 [main] ERROR [o.s.b.SpringApplication] {{appResourceId,vg@dev}} - Application run failed org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.slf4j.impl.SlfTTLogger(org.zalando.logbook.Logbook)] with key 'httpLogger'; nested exception is javax.management.InstanceAlreadyExistsException: MXBean already registered with name org.slf4j.impl.SlfTTLoggerFactory: type=Logger, name=org.zalando.logbook.Logbook
    at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625)
    at org.springframework.jmx.export.MBeanExporter.lambda$registerBeans$2(MBeanExporter.java:551)
    at java.util.HashMap.forEach(HashMap.java:1289)
    at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:551)
    at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:434)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
    at com.company.service.Application.main(Application.java:19)
Caused by: javax.management.InstanceAlreadyExistsException: MXBean already registered with name org.slf4j.impl.SlfTTLoggerFactory: type=Logger, name=org.zalando.logbook.Logbook
    at com.sun.jmx.mbeanserver.MXBeanLookup.addReference(MXBeanLookup.java:151)
    at com.sun.jmx.mbeanserver.MXBeanSupport.register(MXBeanSupport.java:160)
    at com.sun.jmx.mbeanserver.MBeanSupport.preRegister2(MBeanSupport.java:173)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:930)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
    at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
    at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:137)
    at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:671)
    at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:615)
    ... 14 more
2019-01-17 15:53:25,332 4656 [main] INFO  [o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext] {{appResourceId,vg@dev}} - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@40844aab: startup date [Thu Jan 17 15:53:21 IST 2019]; root of context hierarchy
```

This is happening only when I'm using another library that has a dependency on slf4j.

Would it be possible to safeguard against this case in https://github.com/zalando/logbook/blob/master/logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java#L249?

Thanks!

**Comment by whiskeysierra** [comment]
Is the bean name "httpLogger" the issue? I'd hope that Spring JMX would allow you to modify stuff like that in order to avoid conflicts.

**Comment by whiskeysierra** [comment]
Closing doe to inactivity. Feel free to object.
