### ISSUE TITLE
Using JDK 11 getting NoClassDefFoundError

### ISSUE THREAD

**Issue by supadhay** [zalando/logbook#518]
For JDK 11 I am getting ClassDefNotFoundError for Sink class which is part of logbook-api jar whereas for JDK 8 it is working perfectly.
## Description
My code:
 OkHttpClient.Builder okBuilder =
        new OkHttpClient.Builder()
            .readTimeout(Duration.ofSeconds(120))
            .writeTimeout(Duration.ofSeconds(120))
            .addNetworkInterceptor(
                new LogbookInterceptor(
                    Logbook.builder()
                        .headerFilter(authorization())
                        .queryFilter(accessToken())
                        .bodyFilter(bodyFilter)
                        .sink(
                            new DefaultSink(new JsonHttpLogFormatter(), new DefaultHttpLogWriter()))
                        .build()));

Here is the error log

Caused by: java.lang.NoClassDefFoundError: org/zalando/logbook/Sink
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)
	... 44 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.zalando.logbook.Sink
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 48 common frames omitted

## Your Environment

* Version used: 
<dependency>
  <groupId>org.zalando</groupId>
  <artifactId>logbook-api</artifactId>
  <version>2.0.0-RC.1</version>
</dependency>

jdk version: 11.0.3

Let me know if you need more details.

Thanks,
Sanat

**Comment by whiskeysierra** [comment]
I haven't used Java 11 yet. Does it have to do with modules?

**Comment by supadhay** [comment]
Even I have started using jdk 11 recently. If you have any clue on if I missed any module of jdk 11. 
I have look for it if I find any blogs.

**Comment by supadhay** [comment]
There were jar conflicts for logbook-api, Now I am able to solve it. Thanks
