### ISSUE TITLE
Exception while running with Zalando Riptide

### ISSUE THREAD

**Issue by RohanNg** [zalando/logbook#592]
org.zalando.logbook.httpclient.LocalRequest.getHeaders throw java.lang.BootstrapMethodError exception

## Description

While running latest logbook version `2.0.0-RC.3` and riptide version `2.11.0`, I got the follow error:

```
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at org.zalando.logbook.httpclient.LocalRequest.getHeaders(LocalRequest.java:103)
	at org.zalando.logbook.FilteredHttpRequest.<init>(FilteredHttpRequest.java:32)
	at org.zalando.logbook.DefaultLogbookFactory.lambda$combine$2(DefaultLogbookFactory.java:62)
	at org.zalando.logbook.RequestFilter.lambda$merge$1(RequestFilter.java:19)
	at org.zalando.logbook.DefaultLogbook.lambda$process$2(DefaultLogbook.java:39)
	at org.zalando.logbook.httpclient.LogbookHttpRequestInterceptor.process(LogbookHttpRequestInterceptor.java:26)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:182)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.zalando.riptide.httpclient.RestAsyncClientHttpRequest.execute(RestAsyncClientHttpRequest.java:31)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
```

Maybe you can tell why?

**Comment by whiskeysierra** [comment]
I'm guess some version conflict of httpclient. Check what `mvn dependency:tree -D verbose -D includes="*:httpclient"` produces.

**Comment by whiskeysierra** [comment]
In general I'd advise to use Riptide 3.x with Logbook 2.x (using `riptide-logbook` native support).
