### ISSUE TITLE
StackOverflowError for requests with long properties after updating from RC.6 to RC.7

### ISSUE THREAD

**Issue by PascalSchumacher** [zalando/logbook#681]
## Description
After updating from version `2.0.0-RC.6` to `2.0.0-RC.7` we get `StackOverflowError`s for request/responses with long properties (containing base64-encoded content):

```
java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
        at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4941)
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
        at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4713)
        at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3964)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
        at java.base/java.util.regex.Pattern$Start.match(Pattern.java:3619)
        at java.base/java.util.regex.Matcher.search(Matcher.java:1729)
        at java.base/java.util.regex.Matcher.find(Matcher.java:746)
        at org.zalando.logbook.json.JsonBodyFilters.lambda$replace$0(JsonBodyFilters.java:110)
        at org.zalando.logbook.json.JsonBodyFilters$$Lambda$579.00000000126D9220.apply(Unknown Source)
        at org.zalando.logbook.json.JsonBodyFilters.lambda$replace$1(JsonBodyFilters.java:125)
        at org.zalando.logbook.json.JsonBodyFilters$$Lambda$580.00000000126D9730.filter(Unknown Source)
        at org.zalando.logbook.BodyFilter.lambda$merge$1(BodyFilter.java:21)
        at org.zalando.logbook.BodyFilter$$Lambda$582.00000000126DA6C0.filter(Unknown Source)
        at org.zalando.logbook.BodyFilter.lambda$merge$1(BodyFilter.java:21)
        at org.zalando.logbook.BodyFilter$$Lambda$582.00000000126DA6C0.filter(Unknown Source)
        at org.zalando.logbook.FilteredHttpResponse.getBodyAsString(FilteredHttpResponse.java:51)
        at org.zalando.logbook.DefaultHttpLogFormatter.format(DefaultHttpLogFormatter.java:63)
        at org.zalando.logbook.DefaultSink.write(DefaultSink.java:26)
        at org.zalando.logbook.Strategy.write(Strategy.java:119)
        at org.zalando.logbook.DefaultLogbook.lambda$null$0(DefaultLogbook.java:48)
        at org.zalando.logbook.DefaultLogbook$$Lambda$2685.000000003842A100.write(Unknown Source)
        at org.zalando.logbook.okhttp.LogbookInterceptor.intercept(LogbookInterceptor.java:27)
```

## Steps to Reproduce
```java
assertThat(JsonBodyFilters.replaceJsonStringProperty(Collections.singleton("password"), "XXX")
        .filter("application/json",
                "[ {\"longProperty\":\"" + RandomStringUtils.randomAlphabetic(3_000) + "\"}]"))
.isNotNull();
```

By the way: Thank you very much for providing logbook!

**Comment by whiskeysierra** [comment]
Thanks fir the issue. I'll try to take a look.

**Comment by PascalSchumacher** [comment]
Thanks!

I guess the cause is the regex containing repetitive alternative paths added in: cc76205 (see: https://stackoverflow.com/questions/7509905/java-lang-stackoverflowerror-while-using-a-regex-to-parse-big-strings for details)

**Comment by whiskeysierra** [comment]
I prepared #682 as a fix

**Comment by PascalSchumacher** [comment]
Thanks!
