### ISSUE TITLE
java.lang.IllegalStateException: Content has not been provided

### ISSUE THREAD

**Issue by eric239** [zalando/logbook#941]
## Description
Looks like #124 is not fully solved.

I'm applying logbook interceptors to an instance of `HttpClientBuilder` which is wrapped by ElasticSearch client:
```
                httpClientBuilder
                    .addInterceptorFirst(logbookRequestInterceptor)
                    .addInterceptorLast(logbookResponseInterceptor)
```
This produces the same issue as described in #124 
## Expected Behavior

No exception should be raised
## Actual Behavior

```
java.lang.RuntimeException: Content has not been provided
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:857)
.... [skipped irrelevant trace lines] ....
Caused by: java.lang.IllegalStateException: Content has not been provided
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.entity.BasicHttpEntity.getContent(BasicHttpEntity.java:75)
        at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:124)
        at org.zalando.logbook.httpclient.HttpEntities.copy(HttpEntities.java:22)
        at org.zalando.logbook.httpclient.RemoteResponse$Offering.buffer(RemoteResponse.java:76)
        at org.zalando.logbook.httpclient.RemoteResponse.lambda$getBody$2(RemoteResponse.java:186)
        at org.zalando.fauxpas.ThrowingFunction.apply(ThrowingFunction.java:19)
        at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
        at org.zalando.logbook.httpclient.RemoteResponse.getBody(RemoteResponse.java:185)
        at org.zalando.logbook.HttpMessage.getBodyAsString(HttpMessage.java:28)
        at org.zalando.logbook.ForwardingHttpMessage.getBodyAsString(ForwardingHttpMessage.java:47)
        at org.zalando.logbook.FilteredHttpResponse.getBodyAsString(FilteredHttpResponse.java:50)
        at org.zalando.logbook.DefaultHttpLogFormatter.format(DefaultHttpLogFormatter.java:63)
        at org.zalando.logbook.DefaultSink.write(DefaultSink.java:26)
        at org.zalando.logbook.Strategy.write(Strategy.java:119)
        at org.zalando.logbook.DefaultLogbook$1.lambda$process$0(DefaultLogbook.java:55)
        at org.zalando.logbook.httpclient.LogbookHttpResponseInterceptor.process(LogbookHttpResponseInterceptor.java:27)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:142)
...... [skipped the rest of apache http client trace lines].......
```
## Steps to Reproduce
I can provide a self-contained example if needed. It will take some time to factor out (of the real app code), so I'm holding that off initially in case there's something obvious.
## Context

We want to log requests & responses made to ES by our app for troubleshooting and audit purposes.
## Your Environment

* Version used: logbook `2.4.1`, `elasticsearch-rest-client` `7.9.3`

**Comment by whiskeysierra** [comment]
Interesting, haven't seen it heard about this issue since the PR that you linked. Might be something special that ES is doing there, not sure. A minimalistic example to reproduce it would surely help.

**Comment by eric239** [comment]
Understood, @whiskeysierra . I will put together a simple project next week.

**Comment by eric239** [comment]
@whiskeysierra I created [this repo](https://github.com/eric239/logbook-issue-941) to demonstrate the issue. PTAL and let me know if you need anything else. Thanks!

**Comment by whiskeysierra** [comment]
Care to debug send implement the fix yourself?

**Comment by eric239** [comment]
To be clear: you're suggesting that I debug, find a fix myself, and send it?

**Comment by whiskeysierra** [comment]
I don't have the time to work on this any time soon and contributions are highly appreciated. So, yes.

**Comment by fatroom** [comment]
Hi @eric239 thanks for providing sample. 
Problem with ES client in your sample is actually that it's using AsyncHttpClient. 
As logbook readme states - response logging should be done via different way for async http client, since on interceptor execution stage for async client response content is not available.

Since ES client abstracts http operations from you away, I don't see the way how you would be able to log http body with logbook.

**Comment by fatroom** [comment]
BTW, if you interested in logging of request/responses in elastic search client, probably you can specify

```
logging.level.tracer=trace
```

As per https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-low-usage-logging.html

**Comment by eric239** [comment]
well @fatroom how come #125 title is _Fixed async support for http client_ ?
The title led me to believe that the intent was as stated and the original fix simply didn't cover all the edge cases.

I'd be happy to dig deeper into this, but I too lack the necessary time so if the maintainers don't see this as something worthy you might as well close the issue. ES client tracer isn't quite the same thing but I can use it in lieu of logbook support.

**Comment by eric239** [comment]
Closing as there isn't much interest in digging deeper

**Comment by sfilipiak-inpost** [comment]
In case anyone will be looking for an answer in the future, this seems to be working ok (don't mind the spring boot syntax sugar)
```java
    @Bean
    RestClientBuilderCustomizer logbookRestClientBuilderCustomizer(
        LogbookHttpRequestInterceptor logbookHttpRequestInterceptor
    ) {
        return new RestClientBuilderCustomizer() {
            @Override
            public void customize(RestClientBuilder builder) {}

            @Override
            public void customize(HttpAsyncClientBuilder builder) {
                // for logging requests
                builder.addInterceptorLast(logbookHttpRequestInterceptor);
            }
        };
    }

    @Bean
    public RestClientOptions loggingRestClientOptions() {
        var httpAsyncResponseConsumerFactory = new HttpAsyncResponseConsumerFactory() {
            private static final int DEFAULT_BUFFER_LIMIT = Math.toIntExact(DataSize.ofMegabytes(100L).toBytes());

            @Override
            public HttpAsyncResponseConsumer<HttpResponse> createHttpAsyncResponseConsumer() {
                // for logging responses
                return new LogbookHttpAsyncResponseConsumer<>(
                    new SafeResponseConsumer<>(new HeapBufferedAsyncResponseConsumer(DEFAULT_BUFFER_LIMIT)),
                    false
                );
            }
        };
        var requestOptions = RequestOptions.DEFAULT.toBuilder()
            .setHttpAsyncResponseConsumerFactory(httpAsyncResponseConsumerFactory)
            .build();
        return new RestClientOptions(requestOptions);
    }
```
